### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by Aulavik** [oakesville/mythling-epg#19]
Gradle project failed. basic functionality (e.g. editing, debugging) will not work properly.
 my android studio is version 2.13

> ![mythling](https://cloud.githubusercontent.com/assets/15714354/17877078/babfeea6-6912-11e6-86ab-cceaf1b23d18.PNG)

**Comment by oakesville** [comment]
This issue really belongs under [mythling](https://github.com/oakesville/mythling/issues) instead of mythling-epg.
Anyway, please note the Environment Variables section under Build and Run in the wiki dev setup guide:
https://github.com/oakesville/mythling/wiki/Developer-Setup

**Comment by Aulavik** [comment]
Thank you,very much

**Comment by oakesville** [comment]
You're quite welcome.
- Don
